[variables]
NODE_VERSION = "18"
NODE_ENV = "production"

[build]
cmd = "npm install && npm run build"

[start]
cmd = "npx serve -c serve.json -p $PORT"

[phases.install]
dependsOn = []
cmds = ["npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
