[variables]
NODE_VERSION = "18"
NODE_ENV = "production"

[build]
cmd = "npm install && npm run build"

[start]
cmd = "npx http-server dist -p $PORT -a 0.0.0.0 --cors -c-1 --proxy http://localhost:$PORT?"

[phases.install]
dependsOn = []
cmds = ["npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
